azure:
  settings_win:
    pool:
      vmImage: windows-2019
  settings_linux:
    swapfile_size: 10GiB
  free_disk_space: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
